---
title: "Hubble"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(RCurl)
download.file("https://raw.githubusercontent.com/MohamedElashri/Hubble/main/Data/data.csv",destfile="data.csv",method="libcurl")

```
```{r}
z_theme <- function() {
  theme_bw(base_size=9) +
    #Background and Grid formatting
    theme(panel.background=element_rect(fill="#000000", color="#000000")) +
    theme(plot.background=element_rect(fill="#000000", color="#000000")) +
    theme(panel.border=element_rect(color="#252525")) +
    theme(panel.grid.major=element_blank()) +
    theme(panel.grid.minor=element_blank()) +
    #Legend formatting
    theme(legend.background = element_rect(fill="#000000")) +
    theme(legend.text = element_blank()) +
    theme(legend.title= element_blank())+
    theme(legend.position="none")+
    #Axis & Title Formatting
    theme(plot.title=element_text(color="#D9D9D9", size=20, vjust=1.25)) +
    theme(plot.subtitle=element_text(size=12,color="#BDBDBD", vjust=0)) +
    theme(plot.caption=element_text(size=12,color="#BDBDBD", vjust=0)) +
    theme(axis.ticks=element_blank()) +
    theme(axis.text.x=element_text(size=14,color="#BDBDBD")) +
    theme(axis.text.y=element_text(size=14,color="#BDBDBD")) +
    theme(axis.title.x=element_text(size=16,color="#BDBDBD", vjust=0)) +
    theme(axis.title.y=element_text(size=16,color="#BDBDBD", vjust=1.25))
}

```

```{r}
galaxies <- read.csv("data.csv")

```

```{r}
library(ggplot2)
# Convert Distance Modulus to MegaParsecs
galaxies$distmpc<-10^(1+galaxies$mod0/5)/1e6
# Convert Parsecs to Kilometers
galaxies$dist<-galaxies$distmpc*3.085678e+13*1e6

```

```{r}
# Use close galaxies for our estimation
# galaxies2<-subset(galaxies,vgsr<=15000)
galaxies2<-subset(galaxies,distmpc<=250&vgsr<=15000)

ggplot(galaxies2,aes(distmpc,vgsr))+
  geom_point(shape=".",aes(color=vgsr))+
  scale_color_gradientn(colours=c("white","orange","red","darkred"))+
  geom_smooth(method=lm,formula=y~x+0,linetype=4,size=.5,se=F)+
  # scale_x_continuous(limits=c(0,6.15e21))+
  # scale_y_continuous(limits=c(-500,15000))+
  labs(title="The Expanding Universe",
       subtitle="The inverse of the slope of this line is equal to 13.77 billion years",
       x="Distance from Earth (MPc)",
       y="Velocity Away from Earth (km/s)",
       caption="created by /Mohamed Elashri")+
  z_theme()

```


```{r}
ggsave("galaxies.png",dpi=100, height=6, width=9, type="cairo-png")
# Accepted value for Age of Universe:
accage<-13.799e9 # Years

```

```{r}
# Calculate the age of the universe:
calcage<-lm(dist~vgsr+0,data=galaxies2)$coefficients[1]/60/60/24/365.24
paste("Age of Universe:",signif(calcage,5),"years")

paste("Relative Error from accepted Age: ",
            signif(100*(calcage-accage)/accage,5)
            ,"%",sep="")

```

